apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-backend
  namespace: crm-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-backend
  template:
    metadata:
      labels:
        app: crm-backend
    spec:
      initContainers:
      - name: wait-for-db
        image: postgres:15-alpine
        command: ['sh', '-c', 'until pg_isready -h crm-db-service -p 5432 -U postgres; do sleep 2; done']
      - name: db-migrate
        image: azhar1234/crm-backend:latest
        imagePullPolicy: Never
        command: ['bundle', 'exec', 'rails', 'db:prepare']
        env:
        - name: RAILS_ENV
          value: "production"
        - name: DATABASE_URL
          value: "postgresql://postgres:password@crm-db-service:5432/wingmate_production"
        - name: SECRET_KEY_BASE
          value: "dev-secret"
      containers:
      - name: backend
        image: azhar1234/crm-backend:latest
        imagePullPolicy: Never
        command: ['bundle', 'exec', 'rails', 's', '-b', '0.0.0.0']  # Bypass entrypoint
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_ENV
          value: "production"
        - name: DATABASE_URL
          value: "postgresql://postgres:password@crm-db-service:5432/wingmate_production"
        - name: JWT_SECRET
          value: "dev-secret"
        - name: SECRET_KEY_BASE
          value: "dev-secret"
        - name: RAILS_LOG_TO_STDOUT
          value: "true"
        livenessProbe:
          httpGet:
            path: /up
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /up
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 5
        volumeMounts:
        - name: backend-logs
          mountPath: /app/log
      volumes:
      - name: backend-logs
        emptyDir: {}
