apiVersion: v1
kind: ConfigMap
metadata:
  name: crm-config
  namespace: crm-production
data:
  POSTGRES_DB: "wingmate_production"
  POSTGRES_USER: "postgres"
  RAILS_ENV: "production"
  RAILS_LOG_TO_STDOUT: "true"
  RAILS_SERVE_STATIC_FILES: "true"
  PUMA_BIND: "tcp://0.0.0.0:3000"
  DB_PORT: "5432"
  RAILS_PORT: "3000"
  FRONTEND_PORT: "5173"
