apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crm-web.fullname" . }}
  labels:
    {{- include "crm-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "crm-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "crm-web.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: web
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5173
          name: http
        env:
        - name: VITE_API_URL
          value: "/api/v1"
        - name: VITE_PROXY_TARGET
          value: "http://crm-api:3000"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
