apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crm-web.fullname" . }}-secrets
  labels:
    {{- include "crm-web.labels" . | nindent 4 }}
type: Opaque
data:
  # Add your base64 encoded secrets here
   DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
