apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crm-api.fullname" . }}
  labels:
    {{- include "crm-api.labels" . | nindent 4 }}
data:
  RAILS_ENV: {{ .Values.env.RAILS_ENV | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  DATABASE_HOST: {{ .Values.env.DATABASE_HOST | quote }}
  DATABASE_PORT: {{ .Values.env.DATABASE_PORT | quote }}
