apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "crm-api.fullname" . }}-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      {{- include "crm-api.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
